run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - forbidigo
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - stylecheck
    - tenv
    - tparallel
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # blank imports
      - dot # dot imports
      - prefix(github.com/cometbft/cometbft) # comet
      - prefix(cosmossdk.io) # cosmossdk.io
      - prefix(github.com/cosmos/cosmos-sdk) # cosmos-sdk & cosmos org libs
      - prefix(github.com/cosmos/interchain-security) # interchain-security
      - prefix(github.com/cosmos/ibc-go) # ibc
      - prefix( github.com/okp4/okp4d) # okp4
    custom-order: true

  cyclop:
    max-complexity: 20
    skip-tests: true
  funlen:
    statements: 65
  godot:
    scope: declarations # comments to be checked: `declarations` (default), `toplevel`, or `all`
  lll:
    line-length: 135
output:
  uniq-by-line: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - source: "^//\\s*go:generate\\s"
      linters:
        - lll
    - source: '(noinspection|TODO)'
      linters:
        - godot
    - source: '//noinspection'
      linters:
        - gocritic
    - source: "^\\s+if _, ok := err\\.\\([^.]+\\.InternalError\\); ok {"
      linters:
        - errorlint
    - path: "_test\\.go"
      linters:
        - bodyclose
        - dupl
        - funlen
        - goconst
        - noctx
        - unused
        - wrapcheck
