branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: build
          scope: deps
          release: patch
        - type: build
          scope: deps-dev
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch
        - type: docs
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# AXONE protocol changelog"
  - - "semantic-release-replace-plugin"
    - replacements:
        - files: [version]
          from: ^.+$
          to: ${nextRelease.version}
          countMatches: true
          results:
            - file: version
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/exec"
    - prepareCmd: |
        ./scripts/bump-module.sh
  - - "@semantic-release/exec"
    - prepareCmd: |
        make release-assets
  - - "@semantic-release/github"
    - successComment: false
      assets:
        - path: "./target/release/axoned-*-linux-amd64"
        - path: "./target/release/axoned-*-linux-amd64.tar.gz"
        - path: "./target/release/axoned-*-linux-arm64"
        - path: "./target/release/axoned-*-linux-arm64.tar.gz"
        - path: "./target/release/sha256sum.txt"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - version
        - go.mod
        - go.sum
        - "**/*.go"
      message: "chore(release): perform release ${nextRelease.version}"
