name: Build / Proto

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-proto.yml'
      - 'buf.work.yaml'
      - 'Makefile'
      - 'proto/**/*.proto'
      - 'proto/buf.gen.doc.yml'
      - 'proto/buf.gen.gogo.yml'
      - 'proto/buf.yaml'
      - 'scripts/protocgen-code.sh'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/build-proto.yml'
      - 'buf.work.yaml'
      - 'Makefile'
      - 'proto/**/*.proto'
      - 'proto/buf.gen.doc.yml'
      - 'proto/buf.gen.gogo.yml'
      - 'proto/buf.yaml'
      - 'scripts/protocgen-code.sh'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-proto:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build and generate proto
        run: |
          make proto-gen
