name: Build / Go

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-go.yml'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'version'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/build-go.yml'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'version'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-go:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Go environment
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: |
            go.sum

      - name: Build go project
        run: |
          make build-go
