name: Lint / YAML

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/lint-yaml.yml'
      - '**/*.yml'
      - '**/*.yaml'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/lint-yaml.yml'
      - '**/*.yml'
      - '**/*.yaml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
