name: Lint / Proto

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/lint-proto.yml'
      - 'proto/**/*.proto'
      - 'proto/buf.yaml'
      - 'buf.work.yaml'
      - 'flake.nix'
      - 'flake.lock'
      - 'Makefile'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/lint-proto.yml'
      - 'proto/**/*.proto'
      - 'proto/buf.yaml'
      - 'buf.work.yaml'
      - 'flake.nix'
      - 'flake.lock'
      - 'Makefile'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-proto:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Lint proto files
        run: |
          nix develop --command make lint-proto
