name: Lint / Proto

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/lint-proto.yml'
      - 'proto/**/*.proto'
      - 'proto/buf.yaml'
      - 'buf.work.yaml'
      - 'flake.nix'
      - 'flake.lock'
      - 'Makefile'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/lint-proto.yml'
      - 'proto/**/*.proto'
      - 'proto/buf.yaml'
      - 'buf.work.yaml'
      - 'flake.nix'
      - 'flake.lock'
      - 'Makefile'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-proto:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Lint proto files
        run: |
          nix develop --command make lint-proto
