name: Lint / Proto

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/lint-proto.yml'
      - 'proto/**/*.proto'
      - 'proto/buf.yaml'
      - 'buf.work.yaml'
      - 'flake.nix'
      - 'flake.lock'
      - 'Makefile'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/lint-proto.yml'
      - 'proto/**/*.proto'
      - 'proto/buf.yaml'
      - 'buf.work.yaml'
      - 'flake.nix'
      - 'flake.lock'
      - 'Makefile'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-proto:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7

      - name: Lint proto files
        run: |
          nix develop --command make lint-proto
