name: Lint / Generated

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/lint-generated.yml'
      - 'app/**'
      - 'cmd/**'
      - 'docs/command/**'
      - 'docs/predicate/**'
      - 'docs/proto/**'
      - 'go.mod'
      - 'go.sum'
      - 'flake.nix'
      - 'flake.lock'
      - 'Makefile'
      - 'proto/**'
      - 'scripts/**'
      - 'x/**'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/lint-generated.yml'
      - 'app/**'
      - 'cmd/**'
      - 'docs/command/**'
      - 'docs/predicate/**'
      - 'docs/proto/**'
      - 'go.mod'
      - 'go.sum'
      - 'flake.nix'
      - 'flake.lock'
      - 'Makefile'
      - 'proto/**'
      - 'scripts/**'
      - 'x/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-generated:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Generate command documentation
        run: |
          nix develop --command make doc-command

      - name: Generate proto and documentation
        run: |
          nix develop --command make doc-proto

      - name: Generate predicates documentation
        run: |
          nix develop --command make doc-predicate

      - name: Check Git diff in generated files (proto + docs)
        run: |
          if [[ $(git status -s | grep --fixed-strings -v "go.mod" | grep --fixed-strings -v "go.sum") != "" ]]; then
            >&2 echo "❌ There is a diff between generated files and source code"
            >&2 git status
            exit 1
          fi
