name: Project / Add Issue

on:
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  project-add-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/axone-protocol/projects/2
          github-token: ${{ secrets.OPS_TOKEN }}
