name: Publish / Docker Hub Description

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/publish-dockerhub-description.yml'
      - 'README.md'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-dockerhub-description:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5
        with:
          username: ${{ secrets.DOCKER_HUB_REGISTRY_ID }}
          short-description: Docker image for https://github.com/${{ github.repository }}
          password: ${{ secrets.DOCKER_HUB_REGISTRY_TOKEN }}
          repository: axoneprotocol/axoned
          readme-filepath: README.md
