name: Publish / Docker Images

on:
  push:
    branches: [main]
    tags:
      - 'v*'
    paths:
      - '.github/workflows/publish-docker-images.yml'
      - '.dockerignore'
      - 'Dockerfile'
      - '.heighliner/**'
      - 'app/**'
      - 'cmd/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'proto/**'
      - 'scripts/**'
      - 'version'
      - 'x/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-docker-images:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Extract metadata (tags, labels) for Docker
        id: docker_metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: ghcr.io/${{ github.repository }},axoneprotocol/axoned
          tags: |
            type=raw,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},value=nightly
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.vendor=Axone Protocol
            org.opencontainers.image.url=https://axone.xyz
            org.opencontainers.image.documentation=https://docs.axone.xyz

      - name: Login to Docker registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.DOCKER_HUB_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_HUB_REGISTRY_TOKEN }}

      - name: Build and publish image(s)
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
